// <auto-generated />
using InitialMigration.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace InitialMigration.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240816074031_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("InitialMigration.Entities.Course", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.Property<decimal>("Price")
                        .HasPrecision(15, 2)
                        .HasColumnType("decimal(15,2)");

                    b.HasKey("Id");

                    b.ToTable("Courses", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Mathematics",
                            Price = 1000m
                        },
                        new
                        {
                            Id = 2,
                            Name = "Physics",
                            Price = 2000m
                        },
                        new
                        {
                            Id = 3,
                            Name = "Chemistry",
                            Price = 1500m
                        },
                        new
                        {
                            Id = 4,
                            Name = "Biology",
                            Price = 1200m
                        },
                        new
                        {
                            Id = 5,
                            Name = "CS-50",
                            Price = 3000m
                        });
                });

            modelBuilder.Entity("InitialMigration.Entities.Instructor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar");

                    b.HasKey("Id");

                    b.ToTable("Instructors", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Ahmed Abdullah"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Yasmeen Yasmeen"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Khalid Hassan"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Nadia Ali"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Ahmed Abdullah"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
